version: '3.9'
services:

  rstudio:
    build: ./docker/rstudio
    container_name: etl
    environment:
      - PASSWORD=yourpassword
    ports:
      - 8787:8787
    networks:
      - supernet



  mssql:
    build: ./docker/mssql
    container_name: db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rac00ns_@re_Funny
      - MSSQL_PID=Developer
    volumes:
      - ./docker/mssql/db-data:/var/opt/mssql/data
      - ./docker/mssql/scripts:/var/opt/mssql/scripts
    networks:
      - supernet

networks:
  supernet: {}


